// Generates src/styles/tokens.css from docs/design/tokens.json and copies the
// app icons from design/icon, so colours and sizes are never hand-copied
// (spec §8). Run after changing either: `npm run tokens` (in console-ui/).

import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const ui = join(here, '..');
const repo = join(ui, '..');
const tokens = JSON.parse(readFileSync(join(repo, 'docs/design/tokens.json'), 'utf8'));

const lines = [];
const groups = ['surfaces', 'ink', 'accent', 'status', 'station', 'live'];
for (const g of groups) {
  for (const [k, v] of Object.entries(tokens[g])) if (!k.startsWith('$')) lines.push(`  --${k}: ${v};`);
}
lines.push(`  --sans: ${tokens.type.sans.map(f => (f.includes(' ') ? `"${f}"` : f)).join(', ')};`);
lines.push(`  --mono: ${tokens.type.mono.map(f => (f.includes(' ') ? `"${f}"` : f)).join(', ')};`);
for (const [k, v] of Object.entries(tokens.space)) lines.push(`  --space-${k}: ${v}px;`);
for (const [k, v] of Object.entries(tokens.radius)) lines.push(`  --radius-${k}: ${v}px;`);
for (const [k, v] of Object.entries(tokens.size)) lines.push(`  --size-${k}: ${v}px;`);
for (const [k, v] of Object.entries(tokens.motion)) if (!k.startsWith('$') && typeof v === 'string') lines.push(`  --motion-${k}: ${v};`);

const css = `/* GENERATED by scripts/gen-tokens.mjs from docs/design/tokens.json v${tokens.version}. Do not edit. */
:root {
  color-scheme: ${tokens.colorScheme};
${lines.join('\n')}
}
`;
writeFileSync(join(ui, 'src/styles/tokens.css'), css);

// Constants the JS needs (snaps, dim, ranges) come from the same file.
const js = `// GENERATED by scripts/gen-tokens.mjs from docs/design/tokens.json v${tokens.version}. Do not edit.
export const AUDIO = ${JSON.stringify(tokens.audio, null, 2)};
export const STATION_COLORS = ${JSON.stringify(Object.values(tokens.station).filter(v => !String(v).startsWith('The') && v.startsWith('#')))};
export const PHONE_MAX = ${tokens.breakpoints.phone};
`;
writeFileSync(join(ui, 'src/lib/tokens.js'), js);

mkdirSync(join(ui, 'icons'), { recursive: true });
for (const f of ['pwa-192.png', 'pwa-512.png', 'pwa-maskable-512.png', 'crosspoint-32.png']) {
  copyFileSync(join(repo, 'design/icon', f), join(ui, 'icons', f));
}
console.log('tokens.css, tokens.js and icons updated');
