#!/usr/bin/env python3
"""Prepare the per-peer files for a scenario peer (P2.1) and print launch hints.

Usage: peerprep.py <peer-json> <peer-dir> <host> <port> <group> <name>

Scenario peer fields handled here (all optional):
  config      object  -> written as <peer-dir>/config.yaml, peer gets --config
  setup_role  string  -> a minimal --load-setup file whose saved state says
                         "Role: <setup_role>" (to prove the CLI/YAML outrank it)
  setup_state object  -> (P2.3) the same file also carries APVTS params and an
                         input-group monitor gain, e.g. {"params": {"sendchannels": 2,
                         "dry": 1}, "monitor": 1}
  cli_flags   bool    -> false: do NOT pass -c/-g/-n (identity comes from YAML)
  cli_role    string|null -> the --role flag; null = pass none. When the field is
                         absent the harness keeps its legacy rule (pass the
                         peer's `role` unless it is null).

Output, one record per line (tab separated):
  NOCLI                  omit -c/-g/-n
  ROLE<TAB>keep|none|X   how to pass --role
  ARG<TAB>text           extra argument
"""
import json
import os
import sys


def subst(v, ctx):
    if isinstance(v, str):
        for k, val in ctx.items():
            v = v.replace("%" + k + "%", str(val))
        return v
    if isinstance(v, dict):
        return {k: subst(x, ctx) for k, x in v.items()}
    if isinstance(v, list):
        return [subst(x, ctx) for x in v]
    return v


def scalar(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return json.dumps(str(v))  # JSON strings are valid YAML double-quoted scalars


def dump(obj, indent=0):
    pad = "  " * indent
    lines = []
    for k, v in obj.items():
        if isinstance(v, dict):
            lines.append("%s%s:" % (pad, k))
            lines.extend(dump(v, indent + 1))
        elif isinstance(v, list):
            lines.append("%s%s:" % (pad, k))
            lines.extend("%s  - %s" % (pad, scalar(x)) for x in v)
        else:
            lines.append("%s%s: %s" % (pad, k, scalar(v)))
    return lines


def main():
    entry = json.loads(sys.argv[1])
    peer_dir, host, port, group, name = sys.argv[2:7]
    ctx = {"HOST": host, "PORT": port, "GROUP": group, "NAME": name}

    if entry.get("cli_flags") is False:
        print("NOCLI")
    if "cli_role" in entry:
        print("ROLE\t%s" % (entry["cli_role"] or "none"))
    else:
        print("ROLE\tkeep")

    cfg = entry.get("config")
    if cfg is not None:
        path = os.path.join(peer_dir, "config.yaml")
        with open(path, "w") as fh:
            fh.write("# generated by tests/f2/peerprep.py\n")
            fh.write("\n".join(dump(subst(cfg, ctx))) + "\n")
        print("ARG\t--config")
        print("ARG\t%s" % path)

    sr = entry.get("setup_role")
    ss = entry.get("setup_state")   # P2.3: {"params": {id: value}, "monitor": gain, "sendchannels"...}
    if sr or ss:
        path = os.path.join(peer_dir, "setup.settings")
        parts = []
        for pid, val in ((ss or {}).get("params") or {}).items():
            parts.append('<PARAM id="%s" value="%s"/>' % (pid, val))
        if sr:
            parts.append('<ExtraState Role="%s"/>' % sr)
        if ss and "monitor" in ss:
            parts.append('<InputChannelGroups numChanGroups="1"><ChannelGroup numchan="2" monitorlev="%s"/>'
                         '</InputChannelGroups>' % ss["monitor"])
        state = '<State>%s</State>' % "".join(parts)
        esc = (state.replace("&", "&amp;").replace("<", "&lt;")
               .replace(">", "&gt;").replace('"', "&quot;"))
        with open(path, "w") as fh:
            fh.write('<?xml version="1.0" encoding="UTF-8"?>\n<PROPERTIES>\n'
                     '  <VALUE name="filterStateXML" val="%s"/>\n</PROPERTIES>\n' % esc)
        print("ARG\t--load-setup")
        print("ARG\t%s" % path)


main()
