// GENERATED by scripts/gen-tokens.mjs from docs/design/tokens.json v1.0.0. Do not edit.
export const AUDIO = {
  "levelMinDb": -40,
  "levelMaxDb": 6,
  "levelStepDb": 0.5,
  "soloDimDb": -18,
  "panSnaps": [
    -1,
    -0.5,
    0,
    0.5,
    1
  ],
  "panSnapRadius": 0.07,
  "silentInputMinutes": 10
};
export const STATION_COLORS = ["#9085e9","#199e70","#c98500","#bed590"];
export const PHONE_MAX = 640;
